// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcstgiagnijbjcvrsjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjc3RnaWFnbmlqYmpjdnJzandqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTU1NzEsImV4cCI6MjA2NjAzMTU3MX0.kJQkqcgyiekjZD3EYWTXHN7Phs-jsfb0ug74eM2FdFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);